In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data  # Features
y = iris.target  # Target labels

In [3]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
# Initialize the SVM classifier
svm_classifier = SVC(kernel='linear', random_state=42)

In [5]:
# Train the classifier on the training data
svm_classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=42)

In [6]:
# Predict the labels for the test set
y_pred = svm_classifier.predict(X_test)

In [7]:
# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [8]:
# Print the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

Accuracy: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [9]:
# Example prediction
sample = np.array([[5.1, 3.5, 1.4, 0.2]])  # Example data point
prediction = svm_classifier.predict(sample)
print("\nPrediction for sample {}: Class {}".format(sample, prediction))



Prediction for sample [[5.1 3.5 1.4 0.2]]: Class [0]
